require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-i18n

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

# I18n/RailsI18n:
#   Enabled: true
# I18n/GetText:
#   Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

# Metrics/MethodLength:
#   Max: 20

# Metrics/AbcSize:
#   Max: 20

Rails/I18nLocaleTexts:
  Enabled: false